version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"
  
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  user-service:
    build: ./user-service
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "3001:3001"

  todo-service:
    build: ./todo-service
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "3002:3002"
    
  api-gateway:
    build: ./api-gateway
    depends_on:
      - user-service
      - todo-service
      - rabbitmq
    ports:
      - "3000:3000"
  
  sunset-app:
    build: ./sunset-app
    ports:
      - "5173:5173"
    depends_on:
      - api-gateway

volumes:
  postgres_data:
