version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  user-service:
    build: ./user-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      DB_DATABASE: postgres
      DB_SCHEMA: user_schema
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "3001:3001"

  todo-service:
    build: ./todo-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      DB_DATABASE: postgres
      DB_SCHEMA: todo_schema
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "3002:3002"
    
  api-gateway:
    build: ./api-gateway
    environment:
      JWT_ACCESS_SECRET: c9316984e771f607fe2b10442f2f5d4c66183445c362dd1c28b939817a57ad58
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - user-service
      - todo-service
      - rabbitmq
    ports:
      - "3000:3000"

volumes:
  postgres_data:
